export const actionTypes = {
  INDEX: "INDEX",
  NEXT: "NEXT",
  LOADING: "LOADING",
  LOADED: "LOADED",
  GET_VOCABULARIES: "GET_VOCABULARIES",
  CREATE_VOCABULARY: "CREATE_VOCABULARY",
  DELETE_VOCABULARY: "DELETE_VOCABULARY",
  UPDATE_VOCABULARY: "UPDATE_VOCABULARY",
  MASTER_VOCABULARY: "MASTER_VOCABULARY",
  SET_USER: "SET_USER",
  SIGN_OUT: "SIGN_OUT",
};
